channel_sources:
  - nsls2forge,defaults
channel_targets:
  - nsls2forge main
cuda_compiler:                         # [linux64]
  - nvcc                               # [linux64]
cuda_compiler_version:                 # [linux64]
  - None                               # [linux64]
  - 9.2                                # [linux64]
  - 10.0                               # [linux64]
  - 10.1                               # [linux64]
  - 10.2                               # [linux64]
docker_image:                          # [linux]
  - condaforge/linux-anvil-comp7       # [linux64]
  - condaforge/linux-anvil-cuda:9.2    # [linux64]
  - condaforge/linux-anvil-cuda:10.0   # [linux64]
  - condaforge/linux-anvil-cuda:10.1   # [linux64]
  - condaforge/linux-anvil-cuda:10.2   # [linux64]
zip_keys:
  -                                    # [linux64]
    - cuda_compiler_version            # [linux64]
    - docker_image                     # [linux64]
python:
  - 3.6
  - 3.7
  - 3.8
use_simd:
  - True
  - False
