{% set name = "qulacs" %}
{% set version = "0.1.10.1" %}
{% set sha256 = "7c3909ae63d352ed4b1481d63093cb5971c120c7577353e591a323b7a3d41ada" %}
{% set build = 2 %}

{% set arch = "gpu" %}  # [cuda_compiler_version != "None"]
{% set arch = "cpu" %}  # [cuda_compiler_version == "None"]

# enforce "use_simd" exposed to the recipe; "simd" is unused
{% set simd = "1" %}    # [use_simd == "True"]
{% set simd = "0" %}    # [use_simd == "False"]

package:
  name: {{ name|lower }}-conda
  version: {{ version }}

source:
  - url: https://github.com/qulacs/qulacs/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      - setup.patch
      - CMakeList.patch

build:
  skip: true  # [python_impl == "pypy" or not linux]

  # avoid building qulacs-conda when there is no output
  {% if (arch == "gpu" and use_simd == "False") %}
  skip: true
  {% endif %}

outputs:

  {% if not (arch == "gpu" and use_simd == "False") %}

  # this is a metapackage to ensure mutual exclusiveness
  - name: qulacs-mutex
    version: 1.0  # we only bump this when the infrastructure is changed.
    build:
      number: 0   # don't touch this
      string: {{ arch }}
      run_exports:
        - {{ pin_subpackage('qulacs-mutex', exact=True) }}
    requirements: {}
    test:
      commands:
        - echo "qulacs-mutex metapackage is built"

  {% if (arch == "gpu" and use_simd == "True") %}

  - name: {{ name|lower }}-gpu
    version: {{ version }}
    build:
      number: {{ build }}
      script:
        # GCC and GXX are defined by conda-build
        - export C_COMPILER="${GCC}"
        - export CXX_COMPILER="${GXX}"
        - export CUDA_BIN_PATH=/usr/local/cuda/  # bad interaction between cmake and cuda on CF?
        - $PREFIX/bin/python setup_gpu.py install -vv  # "PYTHON" is undefined at this point
      missing_dso_whitelist:
        - '*/libcuda.*'
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("cuda") }}
        - pybind11
        - eigen 3.3.5
        - cmake
      host:
        - python
        - setuptools
      run:
        - python
        - numpy
        - qulacs-mutex 1.0 {{ arch }}
    test:
      imports:
        - qulacs
      files:
        - test_gpu.py
      commands:
        - nvidia-smi
        - python test_gpu.py

  {% elif (arch == "cpu" and use_simd == "True") %}
  # We split the CPU package for with and without SIMD, because otherwise the only
  # difference between the two builds is the build string, which alone would not be
  # sufficient to generate a unique hash; one would get h1234567 instead...
  # TODO(leofang): investigate if there's a better solution

  - name: {{ name|lower }}
    version: {{ version }}
    build:
      number: {{ build + 100 }}  # preferred version
      script:
        # GCC and GXX are defined by conda-build
        - export C_COMPILER="${GCC}"
        - export CXX_COMPILER="${GXX}"
        - $PREFIX/bin/python setup.py install -vv  # "PYTHON" is undefined at this point
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - pybind11
        - eigen 3.3.5
        - cmake
      host:
        - python
        - setuptools
      run:
        - python
        - numpy
        - qulacs-mutex 1.0 {{ arch }}
    test:
      imports:
        - qulacs
      requires:
        - scipy
      source_files:
        - python/test/test_qulacs.py
      commands:
        - python python/test/test_qulacs.py

  {% elif (arch == "cpu" and use_simd == "False") %}

  - name: {{ name|lower }}
    version: {{ version }}
    build:
      number: {{ build }}
      string: py{{ py }}h{{ PKG_HASH }}_{{ build }}_no_simd
      script:
        # GCC and GXX are defined by conda-build
        - export C_COMPILER="${GCC}"
        - export CXX_COMPILER="${GXX}"
        - export CONDA_QULACS_USE_SIMD=No
        - $PREFIX/bin/python setup.py install -vv  # "PYTHON" is undefined at this point
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - pybind11
        - eigen 3.3.5
        - cmake
      host:
        - python
        - setuptools
      run:
        - python
        - numpy
        - qulacs-mutex 1.0 {{ arch }}
    test:
      imports:
        - qulacs
      requires:
        - scipy
      source_files:
        - python/test/test_qulacs.py
      commands:
        - python python/test/test_qulacs.py

  {% else %}
  {% endif %}

  {% endif %}

about:
  home: https://github.com/qulacs/qulacs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Qulacs is a Variational Quantum Circuit Simulator for Quantum Computation Research.

extra:
  recipe-maintainers:
    - leofang
