{% set name = "qulacs" %}
{% set version = "0.1.10.1" %}
{% set sha256 = "7c3909ae63d352ed4b1481d63093cb5971c120c7577353e591a323b7a3d41ada" %}
{% set build = 2 %}

# ensure the variants are defined (needed for conda-smithy)
{% set use_simd = use_simd or "True" %}
{% set cuda_compiler_version = cuda_compiler_version or "undefined" %}

{% if use_simd == "True" %}
{% set build = build + 100 %}  # preferred version
{% set simd_suffix = "" %}
{% else %}
{% set simd_suffix = "_no_simd" %}
{% endif %}

{% if cuda_compiler_version != "undefined" %}
  {% if cuda_compiler_version != "None" %}
    {% set arch = "gpu" %}
    {% set pkg_name = "-gpu" %}
  {% else %}
    {% set arch = "cpu" %}
    {% set pkg_name = "" %}
  {% endif %}
{% endif %}


package:
  name: {{ name|lower }}-conda
  version: {{ version }}

source:
  - url: https://github.com/qulacs/qulacs/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      - setup.patch
      - CMakeList.patch

build:
  skip: true  # [python_impl == "pypy" or not linux]

  # avoid building qulacs-conda when there is no output
  {% if (arch == "gpu" and use_simd == "False") %}
  skip: true
  {% endif %}

outputs:

  {% if not (cuda_compiler_version != "None" and use_simd == "False") %}

  # this is a metapackage to ensure mutual exclusiveness
  - name: qulacs-mutex
    # we only bump this when the infrastructure is changed.
    version: 1.0
    build:
      # don't touch this
      number: 0
      string: {{ arch }}
      run_exports:
        - {{ pin_subpackage('qulacs-mutex', exact=True) }}
    requirements: {}
    test:
      commands:
        - echo "qulacs-mutex metapackage is built"

  - name: "{{ name|lower }}{{ pkg_name }}"
    version: {{ version }}
    build:
      number: {{ build }}
      string: "py{{ py }}h{{ PKG_HASH }}_{{ build }}{{ simd_suffix }}"
      script:
        # GCC and GXX are defined by conda-build
        - export C_COMPILER="${GCC}"
        - export CXX_COMPILER="${GXX}"

        - export CONDA_QULACS_USE_SIMD={{ use_simd }}       # [cuda_compiler_version == "None"]
        - $PREFIX/bin/python setup.py install -vv           # [cuda_compiler_version == "None"]  # "PYTHON" is undefined at this point

        - export CUDA_BIN_PATH=/usr/local/cuda/             # [cuda_compiler_version != "None"]  # bad interaction between cmake and cuda on CF?
        - $PREFIX/bin/python setup_gpu.py install -vv       # [cuda_compiler_version != "None"]  # "PYTHON" is undefined at this point
      missing_dso_whitelist:                                # [cuda_compiler_version != "None"]
        - '*/libcuda.*'                                     # [cuda_compiler_version != "None"]
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("cuda") }}                            # [cuda_compiler_version != "None"]
        - pybind11
        - eigen 3.3.5
        - cmake
      host:
        - python
        - setuptools
      run:
        - python
        - numpy
        - qulacs-mutex 1.0 {{ arch }}
    test:
      imports:
        - qulacs
      requires:                                             # [cuda_compiler_version == "None"]
        - scipy                                             # [cuda_compiler_version == "None"]
      source_files:                                         # [cuda_compiler_version == "None"]
        - python/test/test_qulacs.py                        # [cuda_compiler_version == "None"]
      files:                                                # [cuda_compiler_version != "None"]
        - test_gpu.py                                       # [cuda_compiler_version != "None"]
      commands:
        - python python/test/test_qulacs.py                 # [cuda_compiler_version == "None"]
        - nvidia-smi                                        # [cuda_compiler_version != "None"]
        - python test_gpu.py                                # [cuda_compiler_version != "None"]

 {% else %}
 {% endif %}

about:
  home: https://github.com/qulacs/qulacs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Qulacs is a Variational Quantum Circuit Simulator for Quantum Computation Research.

extra:
  recipe-maintainers:
    - leofang
