{% set name = "qulacs" %}
{% set version = "0.1.10.1" %}
{% set sha256 = "7c3909ae63d352ed4b1481d63093cb5971c120c7577353e591a323b7a3d41ada" %}
{% set build = 2 %}

{% set arch = "gpu" %}  # [cuda_compiler_version != "None"]
{% set arch = "cpu" %}  # [cuda_compiler_version == "None"]


package:
  name: {{ name|lower }}-conda
  version: {{ version }}

source:
  - url: https://github.com/qulacs/qulacs/archive/v{{ version }}.tar.gz
    sha256: {{ sha256 }}
    patches:
      - setup.patch
      - CMakeList.patch

build:
  skip: true  # [python_impl == "pypy" or not linux]

outputs:
  # this is a metapackage to ensure mutual exclusiveness
  - name: qulacs-mutex
    version: 1.0  # we only bump this when the infrastructure is changed.
    build:
      number: 0   # don't touch this
      string: {{ arch }}
      run_exports:
        - {{ pin_subpackage('qulacs-mutex', exact=True) }}
    requirements: {}
    test:
      commands:
        - echo "qulacs-mutex metapackage is built"

  {% if arch == "gpu" %}

  - name: {{ name|lower }}-gpu
    version: {{ version }}
    build:
      number: {{ build }}
      script:
        # GCC and GXX are defined by conda-build
        - export C_COMPILER="${GCC}"
        - export CXX_COMPILER="${GXX}"
        - export CUDA_BIN_PATH=/usr/local/cuda/  # bad interaction between cmake and cuda on CF?
        - $PREFIX/bin/python setup_gpu.py install -vv  # "PYTHON" is undefined at this point
      missing_dso_whitelist:
        - '*/libcuda.*'
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - {{ compiler("cuda") }}
        - pybind11
        - eigen 3.3.5
        - cmake
      host:
        - python
        - setuptools
      run:
        - python
        - numpy
        - qulacs-mutex 1.0 {{ arch }}
    test:
      imports:
        - qulacs
      files:
        - test_gpu.py
      commands:
        - nvidia-smi
        - python test_gpu.py

  {% else %}

  # this forces "use_simd" to be exposed to the recipe...
  {% set simd = True %}     # [use_simd]
  {% set simd = False %}    # [not use_simd]

  - name: {{ name|lower }}
    version: {{ version }}
    build:
      {% if simd %}
      {% set build = build + 100 %}
      {% set label = '' %}
      {% else %}
      {% set label = '_no_simd' %}
      {% endif %}
      number: {{ build }}
      string: py{{ py }}h{{ PKG_HASH }}_{{ build }}{{ label }}
      script:
        # GCC and GXX are defined by conda-build
        - export C_COMPILER="${GCC}"
        - export CXX_COMPILER="${GXX}"
        {% if not simd %}
        - export CONDA_QULACS_USE_SIMD=0
        {% endif %}
        - $PREFIX/bin/python setup.py install -vv  # "PYTHON" is undefined at this point
    requirements:
      build:
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
        - pybind11
        - eigen 3.3.5
        - cmake
      host:
        - python
        - setuptools
      run:
        - python
        - numpy
        - qulacs-mutex 1.0 {{ arch }}
    test:
      imports:
        - qulacs
      requires:
        - scipy
      source_files:
        - python/test/test_qulacs.py
      commands:
        - python python/test/test_qulacs.py

  {% endif %}

about:
  home: https://github.com/qulacs/qulacs
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Qulacs is a Variational Quantum Circuit Simulator for Quantum Computation Research.

extra:
  recipe-maintainers:
    - leofang
