github:
  user_or_org: nsls-ii-forge
channels:
  sources:
    - nsls2forge
    - defaults
  targets:
    - [nsls2forge, main]
channel_priority: flexible
azure:
  user_or_org: nsls2forge
  project_name: nsls2forge
  settings_linux:
    pool: #BNL-machines
      name: BNL-machines
      demands:
        - gpu -equals true
    workspace:
      clean: all
    strategy:
      maxParallel: 1
provider:
  linux: azure
  osx: azure
  win: azure
upload_on_branch: master
docker:
  executable: docker
  run_args: -t --rm --gpus all
